embed_assets: off
# compress_assets: off
# package_assets: off

s3_bucket: <%= ENV['S3_BUCKET'] %>
s3_access_key_id: <%= ENV['S3_KEY_ID'] %>
s3_secret_access_key: <%= ENV['S3_SECRET_KEY'] %>

javascripts:
  box:
    - public/javascripts/admin/jquery.js
  installation:
    - public/javascripts/admin/jquery.js
    - public/javascripts/admin/installation.js
  common:
    - public/javascripts/admin/jquery.js
    - public/javascripts/admin/jquery.ui.js
    - public/javascripts/admin/rails.js
    - public/javascripts/admin/utils.js
    - public/javascripts/admin/plugins/cmd.js
    - public/javascripts/admin/plugins/subscribe.js
    - public/javascripts/admin/plugins/shortcut.js
    - public/javascripts/admin/plugins/toggle.js
    - public/javascripts/admin/plugins/growl.js
    - public/javascripts/admin/plugins/cookie.js
    - public/javascripts/admin/locales/datepicker_de.js
    - public/javascripts/admin/locales/datepicker_fr.js
    - public/javascripts/admin/locales/datepicker_pt-BR.js
    - public/javascripts/admin/locales/datepicker_it.js
    - public/javascripts/admin/application.js
    - public/javascripts/admin/guiders-1.1.0.js
    - public/javascripts/admin/tutorial.js
  custom_fields:
    - public/javascripts/admin/plugins/fancybox.js
    - public/javascripts/admin/plugins/mustache.js
    - public/javascripts/admin/custom_fields.js
  edit_custom_fields:
    - public/javascripts/admin/plugins/tiny_mce/tinymce.js
    - public/javascripts/admin/plugins/json2.js
    - public/javascripts/admin/plugins/fancybox.js
    - public/javascripts/admin/plugins/mustache.js
    - public/javascripts/admin/custom_fields/category.js
    - public/javascripts/admin/custom_fields/has_many.js
  contents:
    - public/javascripts/admin/plugins/tiny_mce/tinymce.js
    - public/javascripts/admin/contents.js
  content_types:
    - public/javascripts/admin/plugins/codemirror/codemirror.min.js
    - public/javascripts/admin/content_types.js
  site:
    - public/javascripts/admin/site.js
    - public/javascripts/admin/plugins/codemirror/codemirror.min.js
  import:
    - public/javascripts/admin/plugins/json2.js
    - public/javascripts/admin/plugins/smartupdater.js
    - public/javascripts/admin/import.js
  account:
    - public/javascripts/admin/account.js
  pages:
    - public/javascripts/admin/pages.js
    - public/javascripts/admin/plugins/menu_toggler.js
  edit_page:
    - public/javascripts/admin/plugins/tiny_mce/tinymce.js
    - public/javascripts/admin/editable_elements.js
    - public/javascripts/admin/pages.js
  image_picker:
    - public/javascripts/admin/plugins/json2.js
    - public/javascripts/admin/plugins/scrollTo.js
    - public/javascripts/admin/plugins/codemirror/codemirror.min.js
    - public/javascripts/admin/plugins/fancybox.js
    - public/javascripts/admin/plugins/plupload/plupload.full.js
    - public/javascripts/admin/plugins/imagepicker.js
  snippets:
    - public/javascripts/admin/snippets.js
  theme_assets:
    - public/javascripts/admin/theme_assets.js

stylesheets:
  ie:
    - public/stylesheets/admin/blueprint/ie.css
  box:
    - public/stylesheets/admin/blueprint/screen.css
    - public/stylesheets/admin/box.css
    - public/stylesheets/admin/safari.css
  common:
    - public/stylesheets/admin/blueprint/screen.css
    - public/stylesheets/admin/layout.css
    - public/stylesheets/admin/jquery/ui.css
    - public/stylesheets/admin/plugins/toggle.css
    - public/stylesheets/admin/menu.css
    - public/stylesheets/admin/buttons.css
    - public/stylesheets/admin/formtastic.css
    - public/stylesheets/admin/formtastic_changes.css
    - public/stylesheets/admin/assets.css
    - public/stylesheets/admin/sites_picker.css
    - public/stylesheets/admin/application.css
    - public/stylesheets/admin/safari.css
    - public/stylesheets/admin/guiders-1.1.0.css
  fancybox:
    - public/stylesheets/admin/plugins/fancybox.css
    - public/stylesheets/admin/fancybox_changes.css
  installation:
    - public/stylesheets/admin/installation.css
  editable_elements:
    - public/stylesheets/admin/editable_elements.css